# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  locale: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
# Uncomment the lines below to configure your website in a second language.
ja:
  locale: ja
  contentDir: content/ja
  title: Chinese website title...
  params:
    description: Site description in Chinese...
  menu:
    main:
      - name: ホーム
        url: '/'
        weight: 1
      - name: 論文
        url: '/#papers'
        weight: 2
      - name: 学会
        url: '/#talks'
        weight: 3
      - name: 経歴
        url: 'experience/'
        weight: 4
      - name: アクセス
        url: 'contact/'
        weight: 5